build:
  cargo build --release

format:
  cargo fmt

lint:
  cargo clippy

try:
  cargo build --release
  gcc -Wall -g -O0 tests/try.c -I. -Ltarget/release/ -ltemplib -o ./tests/try
  LD_LIBRARY_PATH=target/release ./tests/try
