FROM rust:1.91-slim-bookworm

RUN apt-get update && apt-get install -y --no-install-recommends \
    libpq-dev pkg-config libssl-dev ca-certificates git \
    && cargo install cargo-watch \
    && cargo install diesel_cli --no-default-features --features postgres \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /workspace
